[package]
name = "SysMonitoring"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.37.2"
whoami = "1.6.1"
tokio = { version = "1", features = ["full"] }
egui_overlay = "0.9.0"
egui = "0.33.2"
eframe = "0.33.2"
winapi = { version = "0.3", features = ["winuser"] }
env_logger = "0.11.8"
